### ISSUE TITLE
TradingView now allows all chart data to be exported in CSV format.

### ISSUE THREAD

**Issue by hanyoonLDA** [ciphyr/TradingView-data-scraper#14]
Just thought I'd let you know :) Custom indicators, plots, everything. Worked on strategies and studies for me (but only indicator, price data, etc. No strategy data unfortunately). Perhaps it'd be a better direction for this project to automate the process of getting the CSV from them instead of scraping it and running into issues.

**Comment by ciphyr** [comment]
That's great! Thanks for letting me know. I'm personally just after the price and indicator data to train ML quantitative algos.
