### ISSUE TITLE
{"error":"'NoneType' object has no attribute 'get_text'"} . error

### ISSUE THREAD

**Issue by RilRil** [ciphyr/TradingView-data-scraper#3]
Hello, I try to use you tool but I get this error every time 
I'm using this URL : https://tradingview-data.herokuapp.com/quotes?url=https://www.tradingview.com/chart/BTCEUR/bEKjwimr-btceur/

any idea on what's goin on ?
thanks

**Comment by ciphyr** [comment]
Try loading fewer indicators, a shorter timeframe, and/or higher resolution. It's probably a server resource error so you could also try hosting it on a local machine.
