### ISSUE TITLE
{"error":"File is not a zip file"}

### ISSUE THREAD

**Issue by oq19** [ciphyr/TradingView-data-scraper#4]
Hi,

When I try to use this demo link, or my own private charts:
https://tradingview-data.herokuapp.com/quotes?url=https://www.tradingview.com/chart/SPY/vjYfwgMu-SPY-Export-Test/

I get the error:
{"error":"File is not a zip file"}

I have used this tool in the past without issues :/

Please help!

**Comment by ciphyr** [comment]
When I click on that link you pasted up there it downloads a zip for me. Do you still have this issue?

**Comment by oq19** [comment]
Hi!

The problem has been resolved.

Thank you!
