### ISSUE TITLE
How to find a TradingView chart's address?

### ISSUE THREAD

**Issue by rezaee** [ciphyr/TradingView-data-scraper#5]
Hello and thanks for your great work!
I like to know is it possible to read data of this chart for example: http://www.tgju.org/chart/price_dollar_soleymani/trading with your library? How?

**Comment by ciphyr** [comment]
I've updated the ReadMe to include video tutorials.

- How-to screen recording: https://d.pr/v/VGCDNf
- The resulting file from the tutorial above: https://d.pr/f/bnQ75v

Open the embedded chart from your link above in TradingView or simply select the same asset and indicators on TradingView. Then you'll be able to publish the chart and use the tool.
