### ISSUE TITLE
"list index out of range" error

### ISSUE THREAD

**Issue by foxtrotamericana** [ciphyr/TradingView-data-scraper#6]
Great app! I've successfully downloaded your sample data but have been receiving a "list index out of range" error when trying do the same on an idea I've published myself. Can you help me on this? Many thanks

**Comment by sebastianmattos** [comment]
Hi! Thanks so much for doing this, it is so useful. Unfortunately, I am having the same error as foxtrotamericana. I have tried many times, with no indicators and with various time frames and not many bars. I always get an error. 
You also said something about trying to host it on a local machine, is that something that someone with no coding expertise can do? Thanks!

**Comment by foxtrotamericana** [comment]
@sebastianmattos, I was able to resolve my error issue when I realized that the idea I was publishing had a strategy, which i had written myself, associated with the chart. once I published an idea with a clean chart (no indicators, etc) and no strategies associated with it, the script worked! I hope that helps you.
