### ISSUE TITLE
How do I install it on a local machine?

### ISSUE THREAD

**Issue by utopiafusion** [ciphyr/TradingView-data-scraper#9]
I'm running Windows, I'd like to run the code locally, how does it work?

I basically want to still be able to get the CSV using the Python code you listed but I don't know how to program.

Thank you in advance. Great tool!

**Comment by abhishek-githb** [comment]
There are instructions in readme.
You just run the app.py after that

**Comment by gunner69** [comment]
The install instructions is for Windows or Linux? I got stuck at the command "source bin/activate". I find out it's not the Windows command. How can I fix this issue.
